schema:
  - 'src/main/graphql/**/*.graphql'
documents: null
extensions:
  codegen:
    overwrite: true
    generates:
      src/main/graphql/generated/schema.graphql:
        plugins:
          - schema-ast
        config:
          sort: true
      src/main/graphql/generated/index.ts:
        plugins:
          - typescript
          - typescript-resolvers

