schema:
  - src/main/graphql/**/*.graphql
extensions:
  codegen:
    overwrite: true
    generates:
      src/main/graphql/generated/schema.graphql:
        plugins:
        - schema-ast
      src/main/graphql/generated/index.ts:
        plugins:
          - typescript
          - typescript-resolvers
          - typescript-operations
