version: '3.8'
services:
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - './data:/data/db'
    ports:
      - '27018:27017'
  aicrag_dev:
    container_name: aicrag_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - './src/:/usr/aicrag/src/'
    ports:
      - '4000:4000'
      - '9222:9222'
    links:
      - mongo
