FROM node:16-alpine
WORKDIR /usr/aicrag

COPY package.json .
COPY yarn.lock .
RUN yarn install
COPY tsconfig.build.json .
COPY tsconfig.json .
COPY babel.config.js .
COPY .graphqlrc.yml .
COPY .env.development .
COPY ./src ./src
RUN yarn build

CMD ["yarn", "dev:docker"]
