version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - './data:/data/db'
    ports:
      - '27018:27017'
  api:
    container_name: api-container
    image: node:14
    restart: always
    volumes:
      - './dist/:/usr/workspace/aicrag-v2/dist/'
      - './package.json:/usr/workspace/aicrag-v2/package.json'
      - './config.env:/usr/workspace/aicrag-v2/config.env'
    ports:
      - '3000:3000'
      - '9222:9222'
    working_dir: /usr/workspace/aicrag-v2/
    command: bash -c "npm install --only=prod && npm run debug"
    links:
      - mongo
