version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - './data:/data/db'
    ports:
      - '27018:27017'
  api:
    container_name: api-container
    build: .
    restart: always
    volumes:
      - './dist/:/usr/aicrag/dist/'
      - './package.json:/usr/aicrag/package.json'
      - './config.env:/usr/aicrag/config.env'
    ports:
      - '3033:3033'
      - '9222:9222'
    links:
      - mongo
