FROM node:16-alpine
WORKDIR /usr/aicrag
RUN npm install -g pnpm
RUN pnpm add -g pnpm
COPY package.json .
COPY pnpm-lock.yaml .
RUN pnpm install --unsafe-perm
COPY tsconfig.build.json .
COPY tsconfig.json .
COPY babel.config.js .
COPY .graphqlrc.yml .
COPY .env.development .
COPY ./src ./src
RUN pnpm build
CMD ["pnpm", "dev:docker"]
