name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
    - uses: actions/checkout@v2
    name: Check out repository
    - uses: actions/setup-node@v1
    name: Set up Node.js
    with:
      node-version: 16
      env_file: ".env"
    - run: |
        npm run test:ci
    name: Test
    - uses: akhileshns/heroku-deploy@v3.12.12
    with:
      heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      heroku_app_name: "aicrag-v2-backend"
      heroku_email: "christiangama.dev@gmail.com"
      usedocker: true
      env_file: ".env"

